{"uuid": "9c878c91-360c-4e23-8d17-1f07231e9625", "children": ["75fedf33-a5a8-4cd4-bbd2-509c74aeb870"], "befores": [{"name": "user_create", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/buzovao/Desktop/Diplom/Diplom_3/conftest.py\", line 39, in user_create\n    access_token = response.json()['accessToken']\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n"}, "start": 1737138096264, "stop": 1737138096368}], "start": 1737138096264, "stop": 1737138096393}