{"uuid": "1e03f547-4a25-4d7e-8733-bd27791bd5fa", "children": ["a9fcb658-8ee8-4e80-8bbe-486d5463741c"], "befores": [{"name": "user_create", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/buzovao/Desktop/Diplom/Diplom_3/conftest.py\", line 39, in user_create\n    access_token = response.json()['accessToken']\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n"}, "start": 1737137296750, "stop": 1737137296854}], "start": 1737137296750, "stop": 1737137296858}